[metadata]
license = MIT
license_file = LICENSE
classifiers =
    programming Language :: python :: 3.7
    programming Language :: python :: 3.8
    programming Language :: python :: 3.9
    programming Language :: python :: 3.14
    Operating System :: OS Independent

[options]
install_requires =
    ensure==1.0.2
    py-youtube ==1.1.7
python_requires = >=3.7
